name: Run Tests

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set environment variables
        run: |
          echo "LOGIN_TEST_PW=${{ secrets.LOGIN_TEST_PW }}" >> .env
          echo "LOGIN_TEST_USR=${{ secrets.LOGIN_TEST_USR }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
      - name: Install dependencies
        run: npm ci  

      - name: Run tests
        run: npm test
